{"name": "test_4", "status": "skipped", "statusDetails": {"message": "XFAIL reason: bug未修复\n\n_pytest.outcomes.XFailed: bug未修复", "trace": "def test_4():\n>       pytest.xfail(reason=\"bug未修复\")#后续代码不会被执行\nE       _pytest.outcomes.XFailed: bug未修复\n\ntestcases\\test_study.py:113: XFailed"}, "start": 1675225352181, "stop": 1675225352181, "uuid": "004d4aae-efc2-45aa-8057-bdba53b1ce5b", "historyId": "c55b6a71ab35df25558cbde276646b6e", "testCaseId": "bec601f14fce2891718340806c5f73c8", "fullName": "testcases.test_study#test_4", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_study"}, {"name": "host", "value": "LAPTOP-AKAH6LMA"}, {"name": "thread", "value": "11320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_study"}]}